### ISSUE TITLE
application_informations table data

### ISSUE THREAD

**Issue by aankitkumar31** [socioboard/Socioboard-4.0#139]
Hello All,
I just downloaed socioboard4.0 but i am not able to perform any action it shows me **Upgrade your plan in order to use this feature** for every action. could you guys please help me with this.

**Comment by sureshbabu1995** [comment]
Hi @aankitkumar31

**Comment by aankitkumar31** [comment]
Hi @sureshbabu1995 ,
thanks for the update. i had modified the user_plan column in activation table to 7 but now it shows me invalid token error.

**Comment by sureshbabu1995** [comment]
Hi @aankitkumar31 
Just logout and Log-in, every time of login you'll have new tokens, with plan details , if you change plan it's compulsory to get updated ( log-out  & login ) if manually made , else automatically it will get updates, Please check this process, and if you need any information , give me some clarifications via screenshot or video so that I can rectify instantly ( straight forward )
