### ISSUE TITLE
Installing socioboard-api

### ISSUE THREAD

**Issue by JonathanDeBelg** [socioboard/Socioboard-4.0#141]
Hi, im trying to install the socioboard-api part of the installation process. Now i arraived at step 3. I need to run this; sequelize db:migrate but i gives the following error; "error: connect etimedout". Do you guys have any idea of how to fix this. Thanks in advance!

**Comment by sureshbabu1995** [comment]
Hi, @JonathanDeBelg 
**Please check the DB configuration, in the config file,**
 `apis\library\sequelize-cli\config\config.json` and 
check that the values are proper in the development object.

and if possible check the status of connecting db with those values in any other way so that you'll comes to know that the database connection is working properly and Database is running properly

**Comment by JonathanDeBelg** [comment]
Hi, thanks for your reply @sureshbabu1995

Yes a have checked it multiple times, and the values are correct. When giving the wrong database credentials it gives a other error, someting like "ERROR: connenct ECONNREFUSED"
