### ISSUE TITLE
Mongodb API developement and default

### ISSUE THREAD

**Issue by danieladi050** [socioboard/Socioboard-4.0#152]
hello guys i  have some question here
i already read the documentation but got confused in this part

1. where we can see our username password and other aspect of mongodb ? i install the mongodb and start the sevice from cmd like this 

C:\WINDOWS\system32>net start mongodb
The requested service has already been started.

and suddenly i need to input username password etc in delopment default so i got confused. this is my first time using mongodb. usually i only use sql.

2. i dont know how to get the data for the api thing. for example "app_id": "<<specify the facebook app id>>", where do i get the app id ? not to mention we also need similar thing for twitter instagram etc. and what if i dont want to use the paypal part ? just delete it ? thanks

3. this is just a curious question. sql and mongodb is both database right so why this program use 2 database ? why not 1 ?

i watch the video too but all it do is copy and paste and boom its done hahaha. i realise this is a newbie question and maybe most of you think this is not worth your time so i really appreciate anyone who give their time and mind to help me. thank you

**Comment by sureshbabu1995** [comment]
Hi, @danieladi050 

Answers: 
1. [https://prnt.sc/rsqczv](URL) where you can see the credentials of MongoDB, you can replace it.

2. This is related to social integration, If you want to use Facebook services then you should be a developer in the Facebook and then you should create an application through which you'll request the data from Facebook, ( ** this is just an example of Facebook ** ) you can just open the site and search for developer options or else please go through youtube videos hot to get app id of facebook or something then you'll have an idea of what is app_id, client_id, and client_secrete,

3. We are using both Databases because we know that Mongo is better for non-relational huge data handling and SQL is for relational database handling. for the performance and for the storage consideration we are storing the important things in SQL and the rest huge date developed by this application will be stored in MongoDB.


I Hope, this will clear all your doubts.

**Comment by danieladi050** [comment]
thank you for answering, it clear all my doubts. great respect
