### ISSUE TITLE
web login facebook account kit app secret instagram

### ISSUE THREAD

**Issue by danieladi050** [socioboard/Socioboard-4.0#156]
hello,
1. i try to do the document and when i try opening the https://localhost.socioboard.com/, it show that i cant reach the site. but when i try using cmd "php artisan serve" i can go to login page ( localhost : 8000). is this normal ?
ps: this is the continuation from this issue ( https://github.com/socioboard/Socioboard-4.0/issues/155 ) and im still quite confused why theres no command to start web service like php artisan serve in the guide, or how do this project start the web service exactly.

2. i try to register new account but i cant activate it because i receive no email for activation. i try to use testadmin@socioboard.com and pass admin but it told me wrong cred. when i try to register with google account it redirecting the page to another localhost.socioboard.com ( from localhost:8000 ) so another error. 
    "mailService": {
        "defaultMailOption": "gmailServices>",
        "sendgrid": {
            "username": "<<sendgrid username>>",
            "password": "<<sendgrid password>>",
            "frommail": "<<sendgrid frommail>>",
            "ccmail": "<<sendgrid ccmail>>",
            "apiKey": "<<sendgrid apiKey>>"
        },
        "gmailServices": {
            "email": "myemail@gmail.com",
            "password": :**************"
        }
    },

3. i try to use brute force forcing data into db, manage to get in but inside dashboard cant do anything because of the same problem, any button i choose direct me to localhost.sociaboard.com ( problem no 1 ) and get cant reach site again.

4. i try to use brute force again by changing my app url to http://localhost:8000/ and i manage to make it work ( since all page will be directed to http://localhost:8000/ not localhost.sociaboard.com ). when i try to add facebook profile i got "oops, currently not able to add your account". i check the facebook page then i found that i cant fill the account kit app secret because facebook doesnt provide it anymore "Account Kit is no longer available to new developers." since 9 march 2020. is this the reason of the error ? if yes or no how to fix it ? and where do i find the callback url for redirect function in facebook developer sit ?
    "facebook_api": {
        "app_id": "my app id from facebook developer",
        "secret_key": "my secret key from facebook developer",
        "account_kit_version": "v1.1",
        "account_kit_app_secret": "<<specify the account tool kit secret>>",
        "redirect_url": "https://localhost:3000/v1/auth/facebook/callback",
        "fbprofile_add_redirect_url": "https://localhost:3000/v1/team/addSocialProfile",
        "scopes": "email,user_posts,user_birthday,publish_pages,manage_pages,publish_to_groups,user_friends",
        "user_subscription_fields": "feed",
        "page_subscription_fields": "feed",
        "version": "4.0.0"
    }, 
5. based on my knowledge theres a big change in instagram about disabling some of the api, so how do you get webhook token ? is it the same with access token ? and when i try to add instagram i get this error {"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope: []"}. i run this program on localhost:8000 and when i try to add instagram business page, it somehow direct me to facebook.
please help @socioboard @swetasb @Sathish-Globussoft thanks for your time and care

**Comment by sureshbabu1995** [comment]
Hi, @danieladi050 

The Answers are 
1. we use the host files to run the PHP code using xampp instead of direct command for the naming of a website instead of using localhost 

2. check the object once properly for email 
![image](https://user-images.githubusercontent.com/55544386/79537822-b2234500-80a0-11ea-8259-cece649d10fc.png)  and moreover **please check the PHP env and follow tho virtual host process of running the PHP code for better understanding.**

3. I hope u solved that thing in the 4th question itself ( page redirections )

4. it even can run without account kit data also you can simply remove those key-value pairs from that object. and redirect Url you can find it in the Facebook login option under the Oauth redirect URL section. there you add a host URL with proper extensions (as shown in the demo object).

5. Yeah frequently all the Networking API's are getting the update and many sites are deprecating different API's but for the base things  most of the sites are not removing the base features ( like adding account or login through account )

but please keep the objects properly 
![image](https://user-images.githubusercontent.com/55544386/79538540-2e6a5800-80a2-11ea-81ed-d580067625c4.png)

> and my  sincere  suggestion is to try to use PHP running through a virtual host 

**I hope you got Answers for all the above questions.**

**Comment by danieladi050** [comment]
okay thank you very much for your help and time appreciate it @sureshbabu1995
